import { AnalysisReport } from '../analyzer/types';
import {
  generateOverviewSection,
  generateIntentSection,
  generateTopPagesSection,
  generatePatternsSection,
  generateYourPageSection,
  generateRecommendationsSection,
} from './templates';

/**
 * Generate a complete markdown report from analysis results
 */
export function generateMarkdownReport(report: AnalysisReport): string {
  const sections = [
    generateOverviewSection(report),
    generateIntentSection(report),
    generateTopPagesSection(report),
    generatePatternsSection(report),
    generateYourPageSection(report),
    generateRecommendationsSection(report),
  ];

  let markdown = sections.join('\n');

  // Add footer
  markdown += `\n---\n\n`;
  markdown += `*Generated by SEO Intent Analyzer using ${report.model}*\n`;

  return markdown;
}

/**
 * Save report to a file
 */
export async function saveReport(report: AnalysisReport, filePath: string): Promise<void> {
  const { promises: fs } = await import('fs');
  const markdown = generateMarkdownReport(report);
  await fs.writeFile(filePath, markdown, 'utf-8');
  console.log(`[Report] Saved to ${filePath}`);
}
