import { LLMProvider } from '../llm/providers/base';
import { PageData } from '../scraper/types';
import { AIContentAnalysis } from './types';
import { parseJsonFromLLM } from '../utils/json-parser';

/**
 * Analyzes content to detect if it was likely generated by AI
 */
export async function detectAIContent(
  keyword: string,
  pageData: PageData,
  llmProvider: LLMProvider
): Promise<AIContentAnalysis> {
  console.log(`[AI Detector] Analyzing content for AI detection...`);

  const prompt = buildAIDetectionPrompt(keyword, pageData);

  try {
    const response = await llmProvider.generate(prompt, {
      temperature: 0.3,
      maxTokens: 2048,
    });

    const analysis = parseJsonFromLLM(response.content);
    console.log(`[AI Detector] Analysis complete: ${analysis.isLikelyAIGenerated ? 'AI-generated' : 'Human-written'} (confidence: ${analysis.confidenceScore}%)`);

    return analysis as AIContentAnalysis;
  } catch (error) {
    console.error('[AI Detector] Failed to parse AI detection analysis:', error);

    // Return a conservative fallback analysis
    return {
      isLikelyAIGenerated: false,
      confidenceScore: 50,
      indicators: [],
      humanLikeQualities: ['Unable to complete full analysis'],
      aiLikeQualities: [],
      recommendation: 'Manual review recommended - analysis failed',
      summary: 'Unable to complete automated AI detection analysis. Please review content manually.',
    };
  }
}

function buildAIDetectionPrompt(keyword: string, pageData: PageData): string {
  // Extract relevant text content for analysis
  const contentSample = extractContentSample(pageData);

  return `You are an expert at detecting AI-generated content. Analyze the following web page content to determine if it was likely written by a human or generated by AI.

# Page Information
**Keyword**: ${keyword}
**Title**: ${pageData.title || 'N/A'}
**Meta Description**: ${pageData.metaDescription || 'N/A'}
**Word Count**: ${pageData.wordCount || 0}

# Content Sample
${contentSample}

# Headings Structure
${pageData.headings.h1.length > 0 ? `H1: ${pageData.headings.h1.join(', ')}` : 'No H1'}
${pageData.headings.h2.length > 0 ? `H2s: ${pageData.headings.h2.slice(0, 5).join(', ')}${pageData.headings.h2.length > 5 ? '...' : ''}` : 'No H2s'}

# Analysis Instructions

Analyze this content for indicators of AI generation vs human authorship. Consider:

**AI-Generated Indicators:**
1. Overly formulaic or repetitive sentence structures
2. Generic, non-specific statements that could apply to any topic
3. Excessive use of transition words (furthermore, moreover, additionally, etc.)
4. Lack of personal anecdotes, specific examples, or unique insights
5. Perfectly balanced paragraphs with consistent length
6. Overuse of lists and bullet points in a predictable pattern
7. Generic vocabulary without industry jargon or specialized terminology
8. Lack of controversy, strong opinions, or personality
9. Suspiciously comprehensive coverage without depth
10. Repetitive phrasing or concepts presented multiple times

**Human-Written Indicators:**
1. Conversational tone with natural flow and varied sentence structure
2. Specific examples, case studies, or personal experiences
3. Unique insights or perspectives not found in generic content
4. Natural imperfections in writing style
5. Strong authorial voice or personality
6. Industry-specific terminology used correctly and naturally
7. Varied paragraph lengths and organic structure
8. Opinions, biases, or subjective statements
9. References to current events or timely information
10. Humor, idioms, or cultural references

Return your analysis in the following JSON format:

\`\`\`json
{
  "isLikelyAIGenerated": boolean,
  "confidenceScore": number (0-100, where 100 = extremely confident),
  "indicators": [
    {
      "category": "string (e.g., 'Writing Style', 'Content Structure', 'Vocabulary')",
      "signal": "string (specific observation about the content)",
      "impact": "strong" | "moderate" | "weak"
    }
  ],
  "humanLikeQualities": [
    "string (list of qualities that suggest human authorship)"
  ],
  "aiLikeQualities": [
    "string (list of qualities that suggest AI generation)"
  ],
  "recommendation": "string (clear recommendation for the content owner)",
  "summary": "string (2-3 sentence summary of the analysis)"
}
\`\`\`

Be thorough and specific in your analysis. Provide concrete examples from the content when possible.`;
}

function extractContentSample(pageData: PageData): string {
  const { content, wordCount } = pageData;

  if (!content || content.trim().length === 0) {
    return '[No content available for analysis]';
  }

  // Take first ~1000 words for analysis
  const words = content.split(/\s+/);
  const sampleWords = words.slice(0, Math.min(1000, wordCount || words.length));
  const sample = sampleWords.join(' ');

  // Truncate if still too long (for token limits)
  if (sample.length > 4000) {
    return sample.substring(0, 4000) + '...\n\n[Content truncated for analysis]';
  }

  return sample;
}
